---
## Play
- hosts: group_nfs_hosting

  tasks:
    - name: Download wordpress
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /usr/src/wordpress-latest.zip
      changed_when: False
    - name: Unzip wordpress
      unarchive:
        remote_src: yes # The archive is already on the remote machine, not on the control machine
        src: /usr/src/wordpress-latest.zip
        dest: /usr/src
    - name: Copy wordpress to website directories
      synchronize:
        src: /usr/src/wordpress
        dest: "/home/data/{{item.www_directory}}"
      delegate_to: s4.infra
      with_items: "{{ sites }}"
    - name: Delete downloaded archive
      file:
        path: /usr/src/wordpress-latest.zip
        state: absent
      changed_when: False
    - name: Set Permissions for mounted folder
      file:
        path: /home/data
        state: directory
        mode: '0777'
        recurse: yes


- hosts: group_app_hosting

  tasks:
    - name: Copy virtualhosts
      copy:
        src: files/{{ item.conf_file }}
        dest: /etc/apache2/sites-available/{{ item.conf_file }}
      with_items: "{{ sites }}"

    - name: Enable devops.com
      command: a2ensite devops_com
    
    - name: Enable devsec.com
      command: a2ensite devsec_com
    
    - name: Enable devsecops.com
      command: a2ensite devsecops_com

    - name: Reload apache
      command: systemctl reload apache2

    - name: Configure hosts
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 {{item.url}}"
      with_items: "{{ sites }}"
