---
## Play
- hosts: group_app_hosting

  tasks:
    - name: Install NFS Server
      apt:
        name: nfs-kernel-server
    - name: Install apache2 & PHP7
      apt:
        name:
          - apache2
          - php7.3
    - name : Mount nfs server's folder on webservers
      mount:
        path: /mnt/nfs
        src: s4.infra:/home/data
        state: mounted
        fstype: nfs

    # TODO
    # Mount NFS in /mnt/nfs
    # Create virtualhost (port 80)
      
